Added 'wrap-type' option for sentence-wrapping
someth2say/xmlformat pull request #5
Opened 2021-03-24 09:28 UTC by tbazant

* removed default slicing text nodes into sentences with regexp as it collide with `wrap-length`
* introduce a new `wrap-type` option which defaults to `length` (old behavior) and introduces `sentence` value to break lines at sentence break instead of line length

2021-03-24 10:09 UTC, someth2say requested changes
This is amazing! Thanks a lot!
I would propose, for the sake of retro-compatibility, to default the `wrap-type` to `sentence`.

With your consent, I would also take some time to port your changes to Ruby (I can barely do Ruby, but I'll give it a try).

2021-03-24 10:47 UTC, tbazant commented
> This is amazing! Thanks a lot!
you're welcome
> I would propose, for the sake of retro-compatibility, to default the `wrap-type` to `sentence`.
of course, make sentence the default
> 
> With your consent, I would also take some time to port your changes to Ruby (I can barely do Ruby, but I'll give it a try).
i agree on both of your points, go ahead :-)

2021-03-24 12:59 UTC, tbazant commented on bin/xmlformat.pl
> +    "wrap-type" => "length",
```suggestion
    "wrap-type" => "sentence",
```

2021-03-24 13:00 UTC, tbazant commented on bin/xmlformat.pl
> +    "wrap-type" => "length",
```suggestion
    "wrap-type" => "sentence",
```

2021-03-24 13:00 UTC, tbazant reviewed
Make wrap type 'sentence' the default

2021-04-12 11:23 UTC, tbazant commented
@someth2say how does it look with the ruby version of xmlformat ? Do we need the ruby version at all if we have perl one?

2021-04-14 07:09 UTC, someth2say commented
Hi!
I should say yes, the ruby version is mandatory, as many people is using it, and we need consistency.
I hope you don't mind I pushed to your branch the implementation and some tests. 
If you are ok with it, I can merge it and build the container image and cook a release.

2021-04-14 07:14 UTC, someth2say approved these changes

2021-04-14 07:42 UTC, tbazant reviewed
looks good, thanks a lot!

2021-04-15 06:27 UTC, merged

2021-05-13 07:14 UTC, someth2say commented
@all-contributors add @tbazant for code and design

2021-05-13 08:06 UTC, tbazant commented
thanks for adding me there :-)

2021-05-13 09:29 UTC, someth2say commented
Absolutely my pleasure!